
server:
  port: 8888
  
spring:
  cloud:
    config:
      fail-fast: true
      server:
        git:
          uri: https://github.com/victorhugolgr/labs-microservico-spring-cloud
          search-paths: config_server_files